### ISSUE TITLE
Clarifying stroke dash array ordering

### ISSUE THREAD

**Issue by b-wils** [lottie/lottie-spec#107]
The current stroke dash description is a bit sparse and doesn't cover element ordering and what is and isn't valid. For example, is it valid to have multiple dash elements in a row?

I know Skottie ignores the stroke type value and just uses the array ordering for determining the element meaning, which is probably a bug. I haven't checked other players yet to see how they handle stroke dashes.

I'm thinking the following additions to the spec-

1. May have `n` dashes and `n-1` or `n` gaps.
2. Dashes and gaps must be consecutive and alternating, starting with dash.
3. If there are `n-1` gaps, an additional gap with the same length as the first dash is rendered at the end of the sequence.
4. It may have a single offset element. If present, it must be at the start or end of array. (We may want to only allow this at the end of the array, to keep consistency with how bodymovin exports and what at least one player expects.)

**Comment by mbasaglia** [comment]
AFAIK lottie-web ignores the type and uses the name instead :grimacing:

**Comment by fmalita** [comment]
I think the confusing part is that tagged elements seem to suggest that the array order does not matter, when it fact the order is still important.  Maybe we should consider changing the encoding in 2.x, and at least have a separate offset property.


> 3. If there are `n-1` gaps, an additional gap with the same length as the first dash is rendered at the end of the sequence.

Hmm, this diverges from AE's behavior: for an odd number of dash elements, it starts repeating the values from the beginning, but inverted.  E.g. `[dash(64), gap(32), dash(16)]` draws as `[dash(64), gap(32), dash(16), gap(64), dash(32), gap(16)]`: https://skottie.skia.org/7b627bcbb3ebde79a48890ad89110a3b?h=500&l=true&w=500

That is also [aligned with SVG](https://svgwg.org/svg2-draft/painting.html#StrokeDashing), where _"if the list has an odd number of values, then it is repeated to yield an even number of values"_.

We should probably do the same to minimize friction.

**Comment by b-wils** [comment]
> "if the list has an odd number of values, then it is repeated to yield an even number of values".

Ahhh that is the correct behavior I couldn't quite figure out. Labeling the values is somewhat counter-intuitive in that case, if a dash value could also be a gap value when there is an odd number. Though this does follow how AE labels things and we may want a way to distinguish offset from other values, particularly if we ever want to make offset optional.
