### ISSUE TITLE
Please double check the Can-I-Lottie / Skottie Player.

### ISSUE THREAD

**Issue by hermet** [lottie/lottie-spec#11]
Hello, I noticed that the Skottie player doesn't seem to support text. (https://skottie.skia.org/?h=128&w=128) 
It's likely that one of the components needs to be reviewed.

![image](https://github.com/lottie/lottie-spec/assets/3711518/9e51a596-db52-4620-8d7c-6270fa72ab87)

**Comment by jbeta51** [comment]
Hi there, I see this is listed as completed, but in case this comes up again later:
Skottie does support text, and the error was most likely an issue with the site (vs the player itself). I believe we've fixed the bug and text should be rendering. Feel free to file a bug at https://skia.org/docs/dev/contrib/ if text isn't showing in our animation testing site (https://skottie.skia.org)
