### ISSUE TITLE
Is there a PDF version of the spec?

### ISSUE THREAD

**Issue by aztack** [lottie/lottie-spec#30]
Is there a PDF version of the spec which is ready for ChatGPT?

**Comment by mbasaglia** [comment]
not at this time

**Comment by mbasaglia** [comment]
There's not PDF file but there's a single page version now: https://lottie.github.io/lottie-spec/print_page/

You could print to file to get it as a pdf

**Comment by aztack** [comment]
> There's not PDF file but there's a single page version now: https://lottie.github.io/lottie-spec/print_page/
> 
> You could print to file to get it as a pdf

The url return 404

**Comment by mbasaglia** [comment]
ye it changed to https://lottie.github.io/lottie-spec/dev/print_page/ it's gonna be linked from the main page
