### ISSUE TITLE
Property fields not showing on doc page

### ISSUE THREAD

**Issue by b-wils** [lottie/lottie-spec#35]
Example- https://lottie.github.io/lottie-spec/specs/properties/#position-property

It would be helpful if that page had the expected type that it contains. The schema is referenced in the doc generation, but I think it doesn't read the oneOf for the different animated states to produce property table entries. I'm not sure if it would make more sense to update the doc generation to handle this (how are properties merged/resolved?) or try to move some of the content out of the oneOf and into the top level property definition.

**Comment by mbasaglia** [comment]
What do you mean? The docs links to the basic type in the case of position it links to https://lottie.github.io/lottie-spec/specs/values/#vector

**Comment by b-wils** [comment]
I was expecting it to have a table of common properties rather than a link, like the behavior for shapes.

This may be a bit verbose, but will be useful if we add more properties, ex https://github.com/lottie/lottie-spec/pull/33. Maybe that PR should be modified to have the additional fields at the top level?

**Comment by mbasaglia** [comment]
I'm still not sure what you mean

**Comment by b-wils** [comment]
Maybe a picture will help, something like this- 
![image](https://github.com/lottie/lottie-spec/assets/1399576/6e1353fa-2d87-480f-959b-987e105a7696)
