### ISSUE TITLE
Specify the version of the schema

### ISSUE THREAD

**Issue by simbleau** [lottie/lottie-spec#38]
I'm working on a Lottie integration and I've become somewhat frustrated with the ambiguity in versioning. It seems impossible to find older versions of schema and there's no label discerning the version on the [new schema](https://lottie.github.io/lottie-spec/lottie.schema.json).

As far as I know, the [LottieFiles schema](https://lottiefiles.github.io/lottie-docs/schema/lottie.schema.json) is v5.5.2, because the default is added. But I have no confidence that's true.

<img width="662" alt="image" src="https://github.com/lottie/lottie-spec/assets/48108917/a9a15668-2fed-4599-8cd6-a92ca07f4691">

Please add the version to the root of the schema!

**Comment by mbasaglia** [comment]
So the `v` property describes the version of bodymovin used to export the lottie. for the standard spec we're gonna use some different property that will tie the lottie to an official version of the specs.

**Comment by simbleau** [comment]
> So the `v` property describes the version of bodymovin used to export the lottie. for the standard spec we're gonna use some different property that will tie the lottie to an official version of the specs.

Ah, quite confusing! Two versions at play here.

Sounds good, though. Thanks for providing context on the other issue, as well.

**Comment by mbasaglia** [comment]
Done by https://github.com/lottie/lottie-spec/pull/52
