### ISSUE TITLE
Define Spec Publishing Mechanics

### ISSUE THREAD

**Issue by b-wils** [lottie/lottie-spec#64]
Need to figure out how exactly we are releasing the spec and handling versioning, particularly with git branches/tags, and publishing those.

**Comment by mbasaglia** [comment]
This looks promising: https://github.com/jimporter/mike

**Comment by mbasaglia** [comment]
I think we can close this? We have worflows to publish versions using tags.

**Comment by b-wils** [comment]
> I think we can close this? We have worflows to publish versions using tags.

SG. Can you link your PR to this issue?
