### ISSUE TITLE
Multiple keyframes with the same timestamp should probably be permitted

### ISSUE THREAD

**Issue by rgprog** [lottie/lottie-spec#79]
PR #57 recently changed the language surrounding keyframes, so that two consecutive keyframes cannot share the same `t` value.

Behaviour currently differs between implementations, but I like the current behaviour of `lottie-web`: when multiple keyframes share the same `t` value, the keyframe with the highest array index is rendered. I think it would be reasonable to make this behaviour part of the specification.

This will make it possible for exporters to describe discontinuous changes, like this:

<img src="https://github.com/user-attachments/assets/286f101c-27a0-4639-aa53-dc13ac6d79e0" width="512px">

I don't think that discontinuous changes can be created using After Effects, but Lottie may act as an export target for other animation editors, and some of those editors will produce discontinuous changes. This includes [Jitter](https://jitter.video/), who are currently hiring me to work on their Lottie exporter.

Because `t` values do not have to be integers, it would be possible to roughly emulate this behaviour under the current spec by exporting one keyframe at `t = 4.99999` and another at `t = 5`. To me, this seems inelegant and slightly leaky.

**Comment by mbasaglia** [comment]
IMO forcing keyframes to be increasing makes it easier for lottie renderers, you'd need to add extra checks to render the latest keyframe on overlaps. 

I can speak as the maintainer of Glaxnimate (a lottie editor) and overlapping keyframes would make things more complicated there too.

**Comment by rgprog** [comment]
Thanks for your quick response!

How would Glaxnimate behave if it were to import a Lottie file with two neighbouring keyframes at `t = 4.99999` and `t = 5`?

**Comment by mbasaglia** [comment]
It would keep them neighbouring, they'd be shown next to each other in the timeline. If they had the same time, the latest one would overwrite the value previous keyframe at that time.

Btw, wouldn't a difference of 1 frame be enough rather than going for fractional differences?

**Comment by rgprog** [comment]
Snapping to the previous frame would work well if the Lottie animation were guaranteed to be played back at its preferred frame rate (usually 60fps). However, some Lottie renderers will play back animations without snapping to the nearest frame, because this produces more smooth animation on high-refresh-rate displays. For example, when displaying a 60 fps animation on a 75 Hz display, you might see frame 0, frame 0.8, frame 1.6, frame 2.4...

Moving around frames can also make it more difficult to export easings. Looking again at the diagram above:

<img src="https://github.com/user-attachments/assets/286f101c-27a0-4639-aa53-dc13ac6d79e0" width="512px">

If the `t = 10, size = 2` keyframe were changed to `t = 9, size = 2`, the smooth easing would be squashed, and frames 1 through 8 would display the wrong interpolated `size` value. The exporter would be forced to crop the easing instead, which is more difficult than you might expect.

**Comment by mbasaglia** [comment]
One possibility would be to relax the validator while maintaining the wording on the specs until we figure out what the correct behaviour should be across players

**Comment by mbasaglia** [comment]
I created a PR for this, I'm going to close this as further discussion should happen in the PR itself.
