### ISSUE TITLE
Drawing coordinates and `Transform`

### ISSUE THREAD

**Issue by rgprog** [lottie/lottie-spec#83]
This is a [comment on the 1.0 draft spec](https://lottie.github.io/news/lottie-1.0-draft-review/).

The spec leaves some drawing coordinates unspecified. Speaking with colleagues, this seems to be a common pain point for new Lottie developers.

Examples of missing information:
- The order of operations in `Transform`.
    - The rules for inheriting `Transform` from a parent layer.
- The drawing coordinates for image layers and solid colour layers.
- The clipping coordinates for precomp layers.
- The canvas coordinate space (with `(0, 0)` as its top-left and `(w, h)` at its bottom-right).

**Comment by mbasaglia** [comment]
the transform operations are described in this merge request: https://github.com/lottie/lottie-spec/pull/19
