### ISSUE TITLE
Hidden layers

### ISSUE THREAD

**Issue by rgprog** [lottie/lottie-spec#84]
This is a [comment on the 1.0 draft spec](https://lottie.github.io/news/lottie-1.0-draft-review/).

Layers, shapes and modifiers all have the boolean property `hd`, which is a "hidden" flag.

The effect of this flag is mostly unspecified. Open questions:
- Is it valid for `parent` or `tp` to refer to a hidden layer? If so...
    - Is the child of a hidden layer also hidden?
    - Does a hidden parent layer still affect the transform of its child layers?
    - What happens if a layer's parent is hidden, but its grandparent is not?
    - When a matte layer is hidden, does this make its matte target entirely visible, or entirely invisible? Does the answer change when the matte mode is "inverted alpha"?
- When a layer automatically chooses a neighbouring layer as its matte parent, does this skip hidden layers?
- Does a sequential Trim Path modifier ignore hidden shapes?
- Does hidden content have more relaxed validation?  For example...
    - Can a hidden layer and a non-hidden layer share the same `ind`?
    - Can a hidden layer's `refId` point to an asset which doesn't exist?

**Comment by mbasaglia** [comment]
AFAIK hidden layers are simply not rendered visually but everything else is maintained
